project:
  type: website
  output-dir: docs
  pre-render:
    - scripts/update-dates.R
    - scripts/ignore-future-docs.R
  render:
    - index.qmd
    - syllabus.qmd
    - homework/*.qmd
    - project/*.qmd
    - slides/*.qmd


execute:
  cache: true
  freeze: true  # never re-render during project render

website:
  title: "Stat 251 - Data Wrangling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://srvanderplas.github.io/stat-computing-r-python/
        text: Textbook
      - href: syllabus.pdf
        text: Syllabus
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
